(function (global) {
  const APPLICANT = {
    title: "Ms",
    first_name: "Rachel",
    middle_name: "Mary",
    middle_initial: "M",
    last_name: "Smith",
    full_name: "Rachel Mary Smith",
    preferred_name: "Rachel",
    suffix: "",
    email: "rachel.smith@example.com",
    phone: "+1 617 555 0118",
    alternate_phone: "+1 617 555 0189",
    home_phone: "+1 617 555 0118",
    work_phone: "+1 617 555 0147",
    fax: "+1 617 555 0162",
    website: "https://rachel-smith.example",
    username: "rachel.smith",
    password: "HousingDemo!234",
    sex: "Female",
    dob: "1988-03-22",
    dob_month: "03",
    dob_day: "22",
    dob_year: "1988",
    age: "38",
    ssn: "123-45-6789",
    driver_license: "S12345678",
    driver_license_state: "MA",
    driver_license_expiration: "2029-03-22",
    birth_place: "Dakar, Senegal",
    marital_status: "Married",
    citizenship_status: "U.S. Citizen"
  };

  const CO_APPLICANT = {
    title: "Mr",
    first_name: "Marcus",
    middle_name: "Jules",
    middle_initial: "J",
    last_name: "Smith",
    full_name: "Marcus Jules Smith",
    email: "marcus.smith@example.com",
    phone: "+1 857 555 0103",
    employer_name: "Bay State Transit Services",
    job_title: "Fleet Dispatcher",
    start_date: "2020-02-17",
    annual_income: "58200",
    monthly_income: "4850"
  };

  const CURRENT_ADDRESS = {
    address_line_1: "123 Maple Ave",
    address_line_2: "Apt 4B",
    city: "Boston",
    state: "MA",
    country: "United States",
    zip: "02118",
    move_in_date: "2023-08-01",
    monthly_rent: "2100",
    reason_for_leaving: "Need a larger two-bedroom apartment closer to school and work.",
    landlord_name: "Samuel Brooks",
    landlord_phone: "+1 617 555 0191",
    landlord_email: "samuel.brooks@example.com"
  };

  const PREVIOUS_ADDRESS = {
    address_line_1: "47 Elm Street",
    address_line_2: "Unit 12",
    city: "Cambridge",
    state: "MA",
    country: "United States",
    zip: "02139",
    move_in_date: "2021-05-01",
    move_out_date: "2023-07-31",
    monthly_rent: "1850",
    landlord_name: "Harbor Point Realty",
    landlord_phone: "+1 617 555 0135",
    landlord_email: "leasing@harborpoint.example"
  };

  const CURRENT_EMPLOYMENT = {
    employer_name: "Boston Children's Literacy Center",
    job_title: "Program Manager",
    start_date: "2021-05-10",
    supervisor_name: "Leah Carter",
    supervisor_phone: "+1 617 555 0124",
    supervisor_email: "leah.carter@example.org",
    address_line_1: "400 Harrison Ave",
    address_line_2: "Suite 600",
    city: "Boston",
    state: "MA",
    zip: "02118",
    annual_income: "76800",
    monthly_income: "6400",
    additional_income: "900",
    total_monthly_income: "7300"
  };

  const PREVIOUS_EMPLOYMENT = {
    employer_name: "North End Learning Lab",
    job_title: "Operations Coordinator",
    start_date: "2018-01-08",
    end_date: "2021-04-30",
    supervisor_name: "Darren Mills",
    supervisor_phone: "+1 617 555 0168"
  };

  const EMERGENCY_CONTACT = {
    full_name: "Fatou Ndiaye",
    first_name: "Fatou",
    last_name: "Ndiaye",
    relationship: "Sister",
    phone: "+1 617 555 0155",
    email: "fatou.ndiaye@example.com",
    address_line_1: "88 Cedar Street",
    city: "Quincy",
    state: "MA",
    zip: "02169"
  };

  const PERSONAL_REFERENCE = {
    full_name: "Jasmine Carter",
    first_name: "Jasmine",
    last_name: "Carter",
    relationship: "Family Friend",
    phone: "+1 781 555 0142",
    email: "jasmine.carter@example.com"
  };

  const HOUSEHOLD = {
    occupants: "3",
    adults: "2",
    children: "1",
    dependent_name: "Nadia Smith",
    dependent_first_name: "Nadia",
    dependent_last_name: "Smith",
    dependent_relationship: "Daughter",
    dependent_dob: "2016-09-14"
  };

  const VEHICLE = {
    make: "Toyota",
    model: "RAV4",
    year: "2021",
    color: "Blue",
    license_plate: "8KXT214",
    state: "MA"
  };

  const PET = {
    has_pets: "Yes",
    type: "Dog",
    name: "Milo",
    breed: "Beagle Mix",
    weight: "28"
  };

  const APPLICATION_PREFERENCES = {
    desired_move_in_date: "2026-06-15",
    desired_lease_term: "12 months",
    desired_unit_type: "2 Bedroom",
    desired_rent: "2450",
    parking_needed: "1",
    storage_needed: "No",
    smoker: "No",
    voucher_program: "None",
    section8: "No"
  };

  const SCREENING = {
    bankruptcy: "No",
    eviction: "No",
    felony: "No",
    late_rent: "No",
    cosigner: "No"
  };

  const BANKING = {
    bank_name: "Metro Credit Union",
    account_type: "Checking",
    checking_last_four: "4821",
    savings_last_four: "1190",
    available_balance: "12450"
  };

  const PAYMENT = {
    credit_card_type: "Visa",
    credit_card_number: "4111111111111111",
    card_verification_code: "123",
    card_exp_month: "03",
    card_exp_year: "2028",
    card_user_name: "Rachel Smith",
    card_issuing_bank: "Metro Credit Union",
    card_customer_service_phone: "+1 800 555 0100"
  };

  const PROFILE = {
    profile_id: "housing_application_demo",
    profile_name: "housing_application_demo",
    applicant: APPLICANT,
    co_applicant: CO_APPLICANT,
    current_address: CURRENT_ADDRESS,
    previous_address: PREVIOUS_ADDRESS,
    current_employment: CURRENT_EMPLOYMENT,
    previous_employment: PREVIOUS_EMPLOYMENT,
    emergency_contact: EMERGENCY_CONTACT,
    personal_reference: PERSONAL_REFERENCE,
    household: HOUSEHOLD,
    vehicle: VEHICLE,
    pet: PET,
    application_preferences: APPLICATION_PREFERENCES,
    screening: SCREENING,
    banking: BANKING,
    payment: PAYMENT,
    title: APPLICANT.title,
    first_name: APPLICANT.first_name,
    middle_name: APPLICANT.middle_name,
    middle_initial: APPLICANT.middle_initial,
    last_name: APPLICANT.last_name,
    full_name: APPLICANT.full_name,
    preferred_name: APPLICANT.preferred_name,
    email: APPLICANT.email,
    phone: APPLICANT.phone,
    alternate_phone: APPLICANT.alternate_phone,
    home_phone: APPLICANT.home_phone,
    work_phone: APPLICANT.work_phone,
    fax: APPLICANT.fax,
    website: APPLICANT.website,
    username: APPLICANT.username,
    password: APPLICANT.password,
    sex: APPLICANT.sex,
    dob: APPLICANT.dob,
    dob_month: APPLICANT.dob_month,
    dob_day: APPLICANT.dob_day,
    dob_year: APPLICANT.dob_year,
    age: APPLICANT.age,
    ssn: APPLICANT.ssn,
    driver_license: APPLICANT.driver_license,
    driver_license_state: APPLICANT.driver_license_state,
    driver_license_expiration: APPLICANT.driver_license_expiration,
    birth_place: APPLICANT.birth_place,
    marital_status: APPLICANT.marital_status,
    citizenship_status: APPLICANT.citizenship_status,
    address_line_1: CURRENT_ADDRESS.address_line_1,
    address_line_2: CURRENT_ADDRESS.address_line_2,
    city: CURRENT_ADDRESS.city,
    state: CURRENT_ADDRESS.state,
    country: CURRENT_ADDRESS.country,
    zip: CURRENT_ADDRESS.zip,
    current_address_line_1: CURRENT_ADDRESS.address_line_1,
    current_address_line_2: CURRENT_ADDRESS.address_line_2,
    current_city: CURRENT_ADDRESS.city,
    current_state: CURRENT_ADDRESS.state,
    current_zip: CURRENT_ADDRESS.zip,
    current_move_in_date: CURRENT_ADDRESS.move_in_date,
    monthly_rent: CURRENT_ADDRESS.monthly_rent,
    reason_for_leaving: CURRENT_ADDRESS.reason_for_leaving,
    landlord_name: CURRENT_ADDRESS.landlord_name,
    landlord_phone: CURRENT_ADDRESS.landlord_phone,
    landlord_email: CURRENT_ADDRESS.landlord_email,
    previous_address_line_1: PREVIOUS_ADDRESS.address_line_1,
    previous_address_line_2: PREVIOUS_ADDRESS.address_line_2,
    previous_city: PREVIOUS_ADDRESS.city,
    previous_state: PREVIOUS_ADDRESS.state,
    previous_zip: PREVIOUS_ADDRESS.zip,
    previous_move_in_date: PREVIOUS_ADDRESS.move_in_date,
    previous_move_out_date: PREVIOUS_ADDRESS.move_out_date,
    previous_landlord_name: PREVIOUS_ADDRESS.landlord_name,
    previous_landlord_phone: PREVIOUS_ADDRESS.landlord_phone,
    previous_landlord_email: PREVIOUS_ADDRESS.landlord_email,
    company: CURRENT_EMPLOYMENT.employer_name,
    employer_name: CURRENT_EMPLOYMENT.employer_name,
    employer_address_line_1: CURRENT_EMPLOYMENT.address_line_1,
    employer_address_line_2: CURRENT_EMPLOYMENT.address_line_2,
    employer_city: CURRENT_EMPLOYMENT.city,
    employer_state: CURRENT_EMPLOYMENT.state,
    employer_zip: CURRENT_EMPLOYMENT.zip,
    position: CURRENT_EMPLOYMENT.job_title,
    supervisor_name: CURRENT_EMPLOYMENT.supervisor_name,
    supervisor_phone: CURRENT_EMPLOYMENT.supervisor_phone,
    supervisor_email: CURRENT_EMPLOYMENT.supervisor_email,
    employment_start_date: CURRENT_EMPLOYMENT.start_date,
    annual_income: CURRENT_EMPLOYMENT.annual_income,
    monthly_income: CURRENT_EMPLOYMENT.monthly_income,
    additional_income: CURRENT_EMPLOYMENT.additional_income,
    total_monthly_income: CURRENT_EMPLOYMENT.total_monthly_income,
    previous_employer_name: PREVIOUS_EMPLOYMENT.employer_name,
    previous_job_title: PREVIOUS_EMPLOYMENT.job_title,
    previous_employment_start_date: PREVIOUS_EMPLOYMENT.start_date,
    previous_employment_end_date: PREVIOUS_EMPLOYMENT.end_date,
    emergency_contact_name: EMERGENCY_CONTACT.full_name,
    emergency_contact_relationship: EMERGENCY_CONTACT.relationship,
    emergency_contact_phone: EMERGENCY_CONTACT.phone,
    emergency_contact_email: EMERGENCY_CONTACT.email,
    personal_reference_name: PERSONAL_REFERENCE.full_name,
    personal_reference_relationship: PERSONAL_REFERENCE.relationship,
    personal_reference_phone: PERSONAL_REFERENCE.phone,
    personal_reference_email: PERSONAL_REFERENCE.email,
    co_applicant_name: CO_APPLICANT.full_name,
    co_applicant_first_name: CO_APPLICANT.first_name,
    co_applicant_last_name: CO_APPLICANT.last_name,
    co_applicant_email: CO_APPLICANT.email,
    co_applicant_phone: CO_APPLICANT.phone,
    co_applicant_employer: CO_APPLICANT.employer_name,
    co_applicant_job_title: CO_APPLICANT.job_title,
    co_applicant_annual_income: CO_APPLICANT.annual_income,
    co_applicant_monthly_income: CO_APPLICANT.monthly_income,
    occupants: HOUSEHOLD.occupants,
    adults: HOUSEHOLD.adults,
    children: HOUSEHOLD.children,
    dependent_name: HOUSEHOLD.dependent_name,
    dependent_first_name: HOUSEHOLD.dependent_first_name,
    dependent_last_name: HOUSEHOLD.dependent_last_name,
    dependent_relationship: HOUSEHOLD.dependent_relationship,
    dependent_dob: HOUSEHOLD.dependent_dob,
    vehicle_make: VEHICLE.make,
    vehicle_model: VEHICLE.model,
    vehicle_year: VEHICLE.year,
    vehicle_color: VEHICLE.color,
    license_plate: VEHICLE.license_plate,
    vehicle_state: VEHICLE.state,
    has_pets: PET.has_pets,
    pet_type: PET.type,
    pet_name: PET.name,
    pet_breed: PET.breed,
    pet_weight: PET.weight,
    desired_move_in_date: APPLICATION_PREFERENCES.desired_move_in_date,
    desired_lease_term: APPLICATION_PREFERENCES.desired_lease_term,
    desired_unit_type: APPLICATION_PREFERENCES.desired_unit_type,
    desired_rent: APPLICATION_PREFERENCES.desired_rent,
    parking_needed: APPLICATION_PREFERENCES.parking_needed,
    storage_needed: APPLICATION_PREFERENCES.storage_needed,
    smoker: APPLICATION_PREFERENCES.smoker,
    voucher_program: APPLICATION_PREFERENCES.voucher_program,
    section8: APPLICATION_PREFERENCES.section8,
    bankruptcy: SCREENING.bankruptcy,
    eviction: SCREENING.eviction,
    felony: SCREENING.felony,
    late_rent: SCREENING.late_rent,
    cosigner: SCREENING.cosigner,
    bank_name: BANKING.bank_name,
    account_type: BANKING.account_type,
    checking_last_four: BANKING.checking_last_four,
    savings_last_four: BANKING.savings_last_four,
    available_balance: BANKING.available_balance,
    credit_card_type: PAYMENT.credit_card_type,
    credit_card_number: PAYMENT.credit_card_number,
    card_verification_code: PAYMENT.card_verification_code,
    card_exp_month: PAYMENT.card_exp_month,
    card_exp_year: PAYMENT.card_exp_year,
    card_user_name: PAYMENT.card_user_name,
    card_issuing_bank: PAYMENT.card_issuing_bank,
    card_customer_service_phone: PAYMENT.card_customer_service_phone,
    custom_message: "Applying for a two-bedroom apartment with parking, close to transit and school.",
    comments: "Family of three. Seeking a clean, quiet building with in-building laundry and no smoking."
  };

  if (typeof module !== "undefined" && module.exports) {
    module.exports = PROFILE;
  }
  global.FamilyOSHousingMockProfile = PROFILE;
})(typeof globalThis !== "undefined" ? globalThis : this);
